module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  cats_levillagebyca: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor: 0
  color: 0
  colorbutton: 0
  comment: 0
  config: 0
  config_translation: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  geofield: 0
  geolocation: 0
  geolocation_demo: 0
  geolocation_geofield: 0
  geolocation_google_maps: 0
  geolocation_google_maps_demo: 0
  geolocation_google_places_api: 0
  geolocation_google_static_maps: 0
  geolocation_google_static_maps_demo: 0
  geolocation_leaflet: 0
  geolocation_leaflet_demo: 0
  geolocation_yandex: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  image_effects: 0
  imageapi_optimize: 0
  ipstack: 0
  language: 0
  libraries: 0
  link: 0
  locale: 0
  media: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  node: 0
  options: 0
  page_cache: 0
  panelbutton: 0
  password_policy: 0
  password_policy_characters: 0
  password_policy_length: 0
  password_policy_username: 0
  path: 0
  quickedit: 0
  rdf: 0
  redirect404_home: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  slick: 0
  slick_devel: 0
  slick_example: 0
  slick_extras: 0
  slick_ui: 0
  slick_views: 0
  svg_image: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  vem_migrate_oembed: 0
  video_embed_field: 0
  video_embed_media: 0
  video_embed_wysiwyg: 0
  views_bootstrap: 0
  views_data_export: 0
  views_infinite_scroll: 0
  views_show_more: 0
  views_ui: 0
  menu_link_content: 1
  content_translation: 10
  views: 10
  standard: 1000
  eu_cookie_compliance: 1001
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  lesvillagesbyca: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: fr
