id: securite
label: Sécurité
password_reset: 0
langcode: fr
policy_constraints:
  -
    id: password_length
    character_length: 8
    character_operation: minimum
  -
    id: password_username
    disallow_username: true
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: uppercase
  -
    id: password_policy_character_constraint
    character_count: 2
    character_type: numeric
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: special
roles:
  administrator: administrator
  maire_village: maire_village
