display:
  block_1:
    display_options:
      fields:
        nothing_1:
          alter:
            text: 'Go on website'
  block_2:
    display_options:
      fields:
        nothing_1:
          alter:
            text: 'Go on website'
